<?php

namespace Database\Seeders;

use App\Models\CaseRecord;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CaseSeeder extends Seeder
{
    public function run(): void
    {
        $cases = [
            [
                'case_uid' => 'CL-02471', 'case_ref' => 'CA-02471', 'encounter_id' => 'SE-09841',
                'name' => 'Aisha R.', 'gender' => 'Female', 'age' => 34,
                'district' => 'Sanghar', 'tehsil' => 'Sanghar City', 'hub_id' => 'JH-SAN-01',
                'intake_date' => '2026-04-21', 'intake_time' => '10:14', 'mode' => 'Walk-in', 'source' => 'Self',
                'primary_issue' => 'Inheritance', 'secondary_issue' => 'Property', 'urgency' => 'High',
                'pathway' => ['Legal Advice', 'Mediation'],
                'status' => 'Active', 'disposition' => 'adr', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => true,
                'risk' => 'Medium', 'last_update' => '2026-04-22',
                'summary' => 'Widowed mother of three seeking her legal share in ancestral land following husband\'s brothers\' denial of inheritance rights.',
                'language' => 'Urdu', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. F. Hussain',
            ],
            [
                'case_uid' => 'CL-02468', 'case_ref' => 'CA-02468', 'encounter_id' => 'SE-09834',
                'name' => 'Sadia K.', 'gender' => 'Female', 'age' => 22,
                'district' => 'Shaheed Benazirabad', 'tehsil' => 'Nawabshah', 'hub_id' => 'JH-SBA-01',
                'intake_date' => '2026-04-20', 'intake_time' => '14:32', 'mode' => 'Referral', 'source' => 'Shelter',
                'primary_issue' => 'GBV / Family', 'secondary_issue' => 'Documentation', 'urgency' => 'Immediate',
                'pathway' => ['Legal Advice', 'Litigation', 'Referral'],
                'status' => 'Active', 'disposition' => 'litigation', 'sla_met' => true,
                'is_gbv' => true, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => true,
                'risk' => 'High', 'last_update' => '2026-04-22',
                'summary' => 'Survivor of domestic violence referred from Panah Shelter. Seeking protection order and support for separation proceedings.',
                'language' => 'Urdu', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. R. Khan',
            ],
            [
                'case_uid' => 'CL-02465', 'case_ref' => 'CA-02465', 'encounter_id' => 'SE-09825',
                'name' => 'Muhammad I.', 'gender' => 'Male', 'age' => 41,
                'district' => 'Hyderabad', 'tehsil' => 'Latifabad', 'hub_id' => 'JH-HYD-01',
                'intake_date' => '2026-04-18', 'intake_time' => '09:05', 'mode' => 'Walk-in', 'source' => 'Self',
                'primary_issue' => 'Documentation', 'secondary_issue' => null, 'urgency' => 'Medium',
                'pathway' => ['Documentation'],
                'status' => 'Active', 'disposition' => 'advice-only', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => true, 'is_underserved' => true,
                'risk' => 'Low', 'last_update' => '2026-04-21',
                'summary' => 'Daily-wage labourer seeking assistance with CNIC replacement and B-Form for his three children to access education.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => true,
                'assigned_to' => 'T. Panhwar (Paralegal)',
            ],
            [
                'case_uid' => 'CL-02462', 'case_ref' => 'CA-02462', 'encounter_id' => 'SE-09819',
                'name' => 'Zainab M.', 'gender' => 'Female', 'age' => 27,
                'district' => 'Dadu', 'tehsil' => 'Dadu City', 'hub_id' => 'JH-DAD-01',
                'intake_date' => '2026-04-17', 'intake_time' => '11:20', 'mode' => 'Outreach', 'source' => 'Self',
                'primary_issue' => 'Family', 'secondary_issue' => 'Inheritance', 'urgency' => 'Medium',
                'pathway' => ['Mediation'],
                'status' => 'Settlement', 'disposition' => 'adr', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => false,
                'risk' => 'Low', 'last_update' => '2026-04-20',
                'summary' => 'Dispute between siblings over family home. Mediation accepted by all parties.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. S. Abbasi',
            ],
            [
                'case_uid' => 'CL-02459', 'case_ref' => 'CA-02459', 'encounter_id' => 'SE-09812',
                'name' => 'Rani K.', 'gender' => 'Female', 'age' => 38,
                'district' => 'Dadu', 'tehsil' => 'Johi', 'hub_id' => 'JH-DAD-01',
                'intake_date' => '2026-04-16', 'intake_time' => '15:45', 'mode' => 'Outreach', 'source' => 'NGO',
                'primary_issue' => 'Labour', 'secondary_issue' => 'Documentation', 'urgency' => 'High',
                'pathway' => ['Legal Advice', 'Referral'],
                'status' => 'Active', 'disposition' => 'referred', 'sla_met' => false,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => true, 'is_disability' => false, 'is_underserved' => true,
                'risk' => 'Medium', 'last_update' => '2026-04-22',
                'summary' => 'Hindu scheduled-caste worker denied wages by contractor for 4 months. Seeking recovery and CNIC registration.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. P. Kumar',
            ],
            [
                'case_uid' => 'CL-02455', 'case_ref' => 'CA-02455', 'encounter_id' => 'SE-09806',
                'name' => 'Bilal A.', 'gender' => 'Male', 'age' => 15,
                'district' => 'Sukkur', 'tehsil' => 'Sukkur City', 'hub_id' => 'JH-SUK-01',
                'intake_date' => '2026-04-15', 'intake_time' => '10:30', 'mode' => 'Referral', 'source' => 'Police',
                'primary_issue' => 'Criminal', 'secondary_issue' => null, 'urgency' => 'Immediate',
                'pathway' => ['Legal Advice', 'Litigation', 'Referral'],
                'status' => 'Active', 'disposition' => 'litigation', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => true, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => true,
                'risk' => 'High', 'last_update' => '2026-04-22',
                'summary' => 'Juvenile detained during street altercation. Child-protection protocol activated. Parents notified and present.',
                'language' => 'Urdu', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. N. Jatoi',
            ],
            [
                'case_uid' => 'CL-02453', 'case_ref' => 'CA-02453', 'encounter_id' => 'SE-09801',
                'name' => 'Fatima S.', 'gender' => 'Female', 'age' => 44,
                'district' => 'Sanghar', 'tehsil' => 'Malir', 'hub_id' => 'JH-SAN-01',
                'intake_date' => '2026-04-14', 'intake_time' => '13:10', 'mode' => 'Walk-in', 'source' => 'Self',
                'primary_issue' => 'Property', 'secondary_issue' => null, 'urgency' => 'Medium',
                'pathway' => ['Legal Advice', 'Mediation'],
                'status' => 'Closed', 'disposition' => 'adr', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => false,
                'risk' => 'Low', 'last_update' => '2026-04-19',
                'summary' => 'Tenancy dispute with landlord over illegal eviction. Successfully mediated.',
                'language' => 'Urdu', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. F. Hussain',
            ],
            [
                'case_uid' => 'CL-02450', 'case_ref' => 'CA-02450', 'encounter_id' => 'SE-09795',
                'name' => 'Nusrat B.', 'gender' => 'Female', 'age' => 52,
                'district' => 'Shaheed Benazirabad', 'tehsil' => 'Lyari', 'hub_id' => 'JH-SBA-01',
                'intake_date' => '2026-04-12', 'intake_time' => '16:00', 'mode' => 'Digital', 'source' => 'Self',
                'primary_issue' => 'Family', 'secondary_issue' => 'Documentation', 'urgency' => 'Low',
                'pathway' => ['Legal Advice', 'Documentation'],
                'status' => 'Active', 'disposition' => 'advice-only', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => false,
                'risk' => 'Low', 'last_update' => '2026-04-20',
                'summary' => 'Pension access for widow; death certificate and nominee documentation pending.',
                'language' => 'Urdu', 'consent' => true, 'returning_client' => true,
                'assigned_to' => 'T. Panhwar (Paralegal)',
            ],
            [
                'case_uid' => 'CL-02448', 'case_ref' => 'CA-02448', 'encounter_id' => 'SE-09810',
                'name' => 'Imran B.', 'gender' => 'Male', 'age' => 41,
                'district' => 'Sukkur', 'tehsil' => 'Rohri', 'hub_id' => 'JH-SUK-01',
                'intake_date' => '2026-04-11', 'intake_time' => '11:20', 'mode' => 'Walk-in', 'source' => 'Self',
                'primary_issue' => 'Labour', 'secondary_issue' => '', 'urgency' => 'Low',
                'pathway' => ['Legal Advice'],
                'status' => 'Closed', 'disposition' => 'advice-only', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => false,
                'risk' => 'Low', 'last_update' => '2026-04-11',
                'summary' => 'Daily-wage worker disputing two weeks of unpaid wages. Advised on Sindh Industrial Relations Act recovery procedures; declined to pursue formally as employer paid same evening following hub-issued letter.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. N. Jatoi',
            ],
            [
                'case_uid' => 'CL-02446', 'case_ref' => 'CA-02446', 'encounter_id' => 'SE-09805',
                'name' => 'Reshma D.', 'gender' => 'Female', 'age' => 29,
                'district' => 'Hyderabad', 'tehsil' => 'Latifabad', 'hub_id' => 'JH-HYD-01',
                'intake_date' => '2026-04-10', 'intake_time' => '15:45', 'mode' => 'Walk-in', 'source' => 'Community',
                'primary_issue' => 'Family', 'secondary_issue' => '', 'urgency' => 'Low',
                'pathway' => ['Legal Advice'],
                'status' => 'Closed', 'disposition' => 'advice-only', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => true,
                'risk' => 'Low', 'last_update' => '2026-04-10',
                'summary' => 'Marital property query; counselled on rights under Muslim Family Laws Ordinance. Client took information sheet and declined to open a file.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. F. Hussain',
            ],
            [
                'case_uid' => 'CL-02444', 'case_ref' => 'CA-02444', 'encounter_id' => 'SE-09798',
                'name' => 'Bashir A.', 'gender' => 'Male', 'age' => 16,
                'district' => 'Dadu', 'tehsil' => 'Dadu City', 'hub_id' => 'JH-DAD-01',
                'intake_date' => '2026-04-09', 'intake_time' => '09:30', 'mode' => 'Referral', 'source' => 'Police',
                'primary_issue' => 'Criminal', 'secondary_issue' => 'Documentation', 'urgency' => 'Immediate',
                'pathway' => ['Legal Advice', 'Litigation'],
                'status' => 'Active', 'disposition' => 'litigation', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => true, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => true,
                'risk' => 'High', 'last_update' => '2026-04-22',
                'summary' => 'Minor detained after street altercation. Hub representing under Juvenile Justice System Act. Bail filed; diversion to rehabilitation requested.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. P. Kumar',
            ],
            [
                'case_uid' => 'CL-02441', 'case_ref' => 'CA-02441', 'encounter_id' => 'SE-09790',
                'name' => 'Yasmin Q.', 'gender' => 'Female', 'age' => 38,
                'district' => 'Sanghar', 'tehsil' => 'Shahdadpur', 'hub_id' => 'JH-SAN-01',
                'intake_date' => '2026-04-08', 'intake_time' => '13:10', 'mode' => 'Walk-in', 'source' => 'Community',
                'primary_issue' => 'Documentation', 'secondary_issue' => '', 'urgency' => 'Medium',
                'pathway' => ['Legal Advice', 'Referral'],
                'status' => 'Active', 'disposition' => 'referred', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => true, 'is_underserved' => true,
                'risk' => 'Low', 'last_update' => '2026-04-15',
                'summary' => 'Visually impaired client seeking CNIC renewal with disability registration. Referred to NADRA disability desk; loop-closure pending.',
                'language' => 'Urdu', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. F. Hussain',
            ],
            [
                'case_uid' => 'CL-02438', 'case_ref' => 'CA-02438', 'encounter_id' => 'SE-09782',
                'name' => 'Salma R.', 'gender' => 'Female', 'age' => 47,
                'district' => 'Hyderabad', 'tehsil' => 'Qasimabad', 'hub_id' => 'JH-HYD-01',
                'intake_date' => '2026-04-06', 'intake_time' => '10:55', 'mode' => 'Walk-in', 'source' => 'Self',
                'primary_issue' => 'Inheritance', 'secondary_issue' => 'Family', 'urgency' => 'Medium',
                'pathway' => ['Legal Advice', 'Mediation'],
                'status' => 'Active', 'disposition' => 'adr', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => true,
                'risk' => 'Medium', 'last_update' => '2026-04-21',
                'summary' => 'Sisters disputing share of paternal property. Both sides agreed to mediation. Two sittings completed; settlement draft under review.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. F. Hussain',
            ],
            [
                'case_uid' => 'CL-02434', 'case_ref' => 'CA-02434', 'encounter_id' => 'SE-09775',
                'name' => 'Pooja M.', 'gender' => 'Female', 'age' => 31,
                'district' => 'Sanghar', 'tehsil' => 'Sinjhoro', 'hub_id' => 'JH-SAN-01',
                'intake_date' => '2026-04-04', 'intake_time' => '14:00', 'mode' => 'Walk-in', 'source' => 'Community',
                'primary_issue' => 'Documentation', 'secondary_issue' => '', 'urgency' => 'Low',
                'pathway' => ['Legal Advice'],
                'status' => 'Closed', 'disposition' => 'advice-only', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => true, 'is_disability' => false, 'is_underserved' => true,
                'risk' => 'Low', 'last_update' => '2026-04-04',
                'summary' => 'Hindu minority client seeking guidance on marriage registration under Sindh Hindu Marriage Act. Counsel given; client declined to proceed.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. F. Hussain',
            ],
            // --- Cases awaiting manager approval ---
            [
                'case_uid' => 'CL-02431', 'case_ref' => 'CA-02431', 'encounter_id' => 'SE-09768',
                'name' => 'Anwar S.', 'gender' => 'Male', 'age' => 52,
                'district' => 'Hyderabad', 'tehsil' => 'Latifabad', 'hub_id' => 'JH-HYD-01',
                'intake_date' => '2026-04-26', 'intake_time' => '09:15', 'mode' => 'Walk-in', 'source' => 'Self',
                'primary_issue' => 'Property', 'secondary_issue' => 'Family', 'urgency' => 'Medium',
                'pathway' => ['Mediation & ADR'],
                'status' => 'Pending Approval', 'disposition' => 'adr', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => false,
                'risk' => 'Low', 'last_update' => '2026-04-26',
                'pathway_manager' => 'Bilal Ahmed',
                'approval_decision' => 'pending',
                'requested_at' => '2026-04-26T11:00',
                'summary' => 'Brothers contesting subdivision of joint agricultural land. Both have agreed in principle to mediation. Awaiting Mediation Manager approval to schedule first sitting.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. F. Hussain',
            ],
            [
                'case_uid' => 'CL-02428', 'case_ref' => 'CA-02428', 'encounter_id' => 'SE-09760',
                'name' => 'Zubaida B.', 'gender' => 'Female', 'age' => 34,
                'district' => 'Sukkur', 'tehsil' => 'Rohri', 'hub_id' => 'JH-SUK-01',
                'intake_date' => '2026-04-25', 'intake_time' => '14:20', 'mode' => 'Referral', 'source' => 'Police',
                'primary_issue' => 'Criminal', 'secondary_issue' => 'GBV / Family', 'urgency' => 'High',
                'pathway' => ['Representation in Court'],
                'status' => 'Pending Approval', 'disposition' => 'litigation', 'sla_met' => true,
                'is_gbv' => true, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => true,
                'risk' => 'High', 'last_update' => '2026-04-25',
                'pathway_manager' => 'Irfan Nawaz',
                'approval_decision' => 'pending',
                'requested_at' => '2026-04-25T15:45',
                'summary' => 'GBV survivor seeking court protection order. Police FIR filed. Litigation pathway requires Litigation Manager approval given resource implications and high-risk profile.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. N. Jatoi',
            ],
            [
                'case_uid' => 'CL-02426', 'case_ref' => 'CA-02426', 'encounter_id' => 'SE-09755',
                'name' => 'Kabir M.', 'gender' => 'Male', 'age' => 39,
                'district' => 'Dadu', 'tehsil' => 'Khairpur Nathan Shah', 'hub_id' => 'JH-DAD-01',
                'intake_date' => '2026-04-23', 'intake_time' => '10:50', 'mode' => 'Walk-in', 'source' => 'Community',
                'primary_issue' => 'Civil Litigation', 'secondary_issue' => '', 'urgency' => 'Medium',
                'pathway' => ['Representation in Court'],
                'status' => 'Rejected', 'disposition' => 'advice-only', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => false,
                'risk' => 'Low', 'last_update' => '2026-04-24',
                'pathway_manager' => 'Irfan Nawaz',
                'approval_decision' => 'rejected',
                'rejection_reason' => 'Case lacks sufficient documentary evidence to sustain civil suit. Recommend client first pursue informal resolution through community mediation; may resubmit with stronger evidence base if that path fails.',
                'rejected_by' => 'Irfan Nawaz · Litigation Manager',
                'rejected_at' => '2026-04-24T16:30',
                'requested_at' => '2026-04-23T11:30',
                'summary' => 'Civil suit over disputed loan repayment. Litigation Manager declined court pathway pending stronger evidence; case redirected to informal resolution.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. P. Kumar',
            ],
            // --- Backfilled cases ---
            [
                'case_uid' => 'CL-02469', 'case_ref' => 'CA-02469', 'encounter_id' => 'SE-09839',
                'name' => 'Mahnoor S.', 'gender' => 'Female', 'age' => 26,
                'district' => 'Sanghar', 'tehsil' => 'Sanghar City', 'hub_id' => 'JH-SAN-01',
                'intake_date' => '2026-04-26', 'intake_time' => '10:14', 'mode' => 'Walk-in', 'source' => 'Self',
                'primary_issue' => 'Family', 'secondary_issue' => 'Khula', 'urgency' => 'Medium',
                'pathway' => ['Legal Advice', 'Mediation'],
                'status' => 'Active', 'disposition' => 'adr', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => false,
                'risk' => 'Medium', 'last_update' => '2026-04-28',
                'summary' => 'Young woman seeking dissolution of marriage through Khula. Husband disputed grounds; mediation pathway opened to attempt amicable separation before family court filing.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. R. Khan',
            ],
            [
                'case_uid' => 'CL-02467', 'case_ref' => 'CA-02467', 'encounter_id' => 'SE-09837',
                'name' => 'Iqbal S.', 'gender' => 'Male', 'age' => 52,
                'district' => 'Hyderabad', 'tehsil' => 'Latifabad', 'hub_id' => 'JH-HYD-01',
                'intake_date' => '2026-04-24', 'intake_time' => '10:14', 'mode' => 'Walk-in', 'source' => 'Community',
                'primary_issue' => 'Property', 'secondary_issue' => 'Boundary dispute', 'urgency' => 'Low',
                'pathway' => ['Legal Advice', 'Mediation'],
                'status' => 'Active', 'disposition' => 'adr', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => false,
                'risk' => 'Low', 'last_update' => '2026-04-28',
                'summary' => 'Smallholder farmer in dispute with adjacent landowner over boundary wall built two feet onto his plot. Both parties willing to mediate before approaching revenue authority.',
                'language' => 'Urdu', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. S. Abbasi',
            ],
            [
                'case_uid' => 'CL-02460', 'case_ref' => 'CA-02460', 'encounter_id' => 'SE-09817',
                'name' => 'Hassan A.', 'gender' => 'Male', 'age' => 34,
                'district' => 'Shaheed Benazirabad', 'tehsil' => 'Nawabshah', 'hub_id' => 'JH-SBA-01',
                'intake_date' => '2026-04-15', 'intake_time' => '10:14', 'mode' => 'Walk-in', 'source' => 'Community',
                'primary_issue' => 'Labour', 'secondary_issue' => 'Wage recovery', 'urgency' => 'High',
                'pathway' => ['Legal Advice', 'Mediation'],
                'status' => 'Active', 'disposition' => 'adr', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => true, 'is_disability' => false, 'is_underserved' => true,
                'risk' => 'Medium', 'last_update' => '2026-04-28',
                'summary' => 'Christian construction worker owed four months\' wages by sub-contractor. Mediation initiated to recover arrears (Rs. 168,000) without escalating to labour court.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. P. Kumar',
            ],
            [
                'case_uid' => 'CL-02458', 'case_ref' => 'CA-02458', 'encounter_id' => 'SE-09814',
                'name' => 'Gulnaz R.', 'gender' => 'Female', 'age' => 31,
                'district' => 'Sukkur', 'tehsil' => 'Sukkur City', 'hub_id' => 'JH-SUK-01',
                'intake_date' => '2026-04-14', 'intake_time' => '09:05', 'mode' => 'Phone', 'source' => 'Community',
                'primary_issue' => 'Family', 'secondary_issue' => 'Maintenance', 'urgency' => 'High',
                'pathway' => ['Legal Advice', 'Mediation'],
                'status' => 'Active', 'disposition' => 'adr', 'sla_met' => true,
                'is_gbv' => true, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => true,
                'risk' => 'High', 'last_update' => '2026-04-28',
                'summary' => 'Mother of two seeking court-enforceable maintenance from estranged husband. Historical GBV pattern documented; safe-mediation protocol in place with separate session rooms.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. N. Jatoi',
            ],
            [
                'case_uid' => 'CL-02454', 'case_ref' => 'CA-02454', 'encounter_id' => 'SE-09810',
                'name' => 'Dilawar K.', 'gender' => 'Male', 'age' => 47,
                'district' => 'Dadu', 'tehsil' => 'Mehar', 'hub_id' => 'JH-DAD-01',
                'intake_date' => '2026-04-14', 'intake_time' => '10:14', 'mode' => 'Walk-in', 'source' => 'Self',
                'primary_issue' => 'Land', 'secondary_issue' => 'Tenancy', 'urgency' => 'Medium',
                'pathway' => ['Legal Advice', 'Mediation'],
                'status' => 'Active', 'disposition' => 'adr', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => false,
                'risk' => 'Medium', 'last_update' => '2026-04-28',
                'summary' => 'Tenant farmer of 14 years in dispute with new landowner who is attempting to terminate the tenancy without compensation for standing crop. Mediation underway.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. M. Soomro',
            ],
            [
                'case_uid' => 'CL-02456', 'case_ref' => 'CA-02456', 'encounter_id' => 'SE-09812',
                'name' => 'Kausar B.', 'gender' => 'Female', 'age' => 38,
                'district' => 'Sanghar', 'tehsil' => 'Sanghar City', 'hub_id' => 'JH-SAN-01',
                'intake_date' => '2026-04-07', 'intake_time' => '15:40', 'mode' => 'Walk-in', 'source' => 'Self',
                'primary_issue' => 'Inheritance', 'secondary_issue' => 'Share release', 'urgency' => 'Medium',
                'pathway' => ['Legal Advice', 'Mediation'],
                'status' => 'Active', 'disposition' => 'adr', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => false,
                'risk' => 'Low', 'last_update' => '2026-04-28',
                'summary' => 'Widow seeking release of her late husband\'s share of agricultural land held jointly with his brothers. Three mediation sessions completed; settlement agreement now in drafting.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. F. Hussain',
            ],
            [
                'case_uid' => 'CL-02451', 'case_ref' => 'CA-02451', 'encounter_id' => 'SE-09807',
                'name' => 'Rafiq & Nadia', 'gender' => 'Couple', 'age' => 33,
                'district' => 'Hyderabad', 'tehsil' => 'Latifabad', 'hub_id' => 'JH-HYD-01',
                'intake_date' => '2026-04-01', 'intake_time' => '11:32', 'mode' => 'Walk-in', 'source' => 'Self',
                'primary_issue' => 'Family', 'secondary_issue' => 'Reconciliation', 'urgency' => 'Low',
                'pathway' => ['Legal Advice', 'Mediation'],
                'status' => 'Active', 'disposition' => 'adr', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => false,
                'risk' => 'Low', 'last_update' => '2026-04-28',
                'summary' => 'Couple separated for nine months pursuing reconciliation through structured mediation. Four sessions completed; reconciliation agreement now being drafted with shared-parenting terms.',
                'language' => 'Urdu', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. R. Khan',
            ],
            [
                'case_uid' => 'CL-02449', 'case_ref' => 'CA-02449', 'encounter_id' => 'SE-09805',
                'name' => 'Nasreen W.', 'gender' => 'Female', 'age' => 29,
                'district' => 'Shaheed Benazirabad', 'tehsil' => 'Nawabshah', 'hub_id' => 'JH-SBA-01',
                'intake_date' => '2026-04-14', 'intake_time' => '09:05', 'mode' => 'Referral', 'source' => 'Shelter',
                'primary_issue' => 'GBV', 'secondary_issue' => 'Custody', 'urgency' => 'Immediate',
                'pathway' => ['Legal Advice', 'Mediation', 'Litigation', 'Court'],
                'status' => 'Active', 'disposition' => 'litigation', 'sla_met' => true,
                'is_gbv' => true, 'is_child' => true, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => true,
                'risk' => 'High', 'last_update' => '2026-04-28',
                'summary' => 'Survivor of severe domestic violence with two minor children. ADR attempted but discontinued after one session due to safety risk; case escalated to court for protection order and interim custody.',
                'language' => 'Urdu', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. R. Khan',
            ],
            [
                'case_uid' => 'CL-02445', 'case_ref' => 'CA-02445', 'encounter_id' => 'SE-09801',
                'name' => 'Ghulam M.', 'gender' => 'Male', 'age' => 56,
                'district' => 'Dadu', 'tehsil' => 'Mehar', 'hub_id' => 'JH-DAD-01',
                'intake_date' => '2026-04-03', 'intake_time' => '10:14', 'mode' => 'Walk-in', 'source' => 'Self',
                'primary_issue' => 'Land', 'secondary_issue' => 'Boundary dispute', 'urgency' => 'Medium',
                'pathway' => ['Legal Advice', 'Mediation', 'Litigation', 'Court'],
                'status' => 'Active', 'disposition' => 'litigation', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => false,
                'risk' => 'Medium', 'last_update' => '2026-04-28',
                'summary' => 'Smallholder in protracted boundary dispute with neighbouring landowner. Mediation attempted twice; respondent refused to engage further. Civil suit for declaration filed.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. M. Soomro',
            ],
            [
                'case_uid' => 'CL-02463', 'case_ref' => 'CA-02463', 'encounter_id' => 'SE-09821',
                'name' => 'Rabia S.', 'gender' => 'Female', 'age' => 35,
                'district' => 'Sanghar', 'tehsil' => 'Sanghar City', 'hub_id' => 'JH-SAN-01',
                'intake_date' => '2026-04-17', 'intake_time' => '09:05', 'mode' => 'Walk-in', 'source' => 'Self',
                'primary_issue' => 'Family', 'secondary_issue' => 'Custody', 'urgency' => 'High',
                'pathway' => ['Legal Advice', 'Litigation', 'Court'],
                'status' => 'Active', 'disposition' => 'litigation', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => true, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => false,
                'risk' => 'Medium', 'last_update' => '2026-04-28',
                'summary' => 'Mother seeking custody of three children (ages 4, 7, 11) following separation. Custody petition filed in Family Court; first hearing scheduled for early May.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. F. Hussain',
            ],
            [
                'case_uid' => 'CL-02452', 'case_ref' => 'CA-02452', 'encounter_id' => 'SE-09806',
                'name' => 'Naseem A.', 'gender' => 'Male', 'age' => 41,
                'district' => 'Shaheed Benazirabad', 'tehsil' => 'Nawabshah', 'hub_id' => 'JH-SBA-01',
                'intake_date' => '2026-03-01', 'intake_time' => '14:17', 'mode' => 'Walk-in', 'source' => 'Community',
                'primary_issue' => 'Criminal', 'secondary_issue' => 'False accusation', 'urgency' => 'High',
                'pathway' => ['Legal Advice', 'Litigation', 'Court'],
                'status' => 'Active', 'disposition' => 'litigation', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => true,
                'risk' => 'High', 'last_update' => '2026-04-28',
                'summary' => 'Defendant in criminal proceedings alleging theft; client maintains the FIR was registered maliciously by a former employer. Six hearings held; defence cross-examination of key witness ongoing.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. R. Khan',
            ],
            [
                'case_uid' => 'CL-02447', 'case_ref' => 'CA-02447', 'encounter_id' => 'SE-09803',
                'name' => 'Bashir A.', 'gender' => 'Male', 'age' => 16,
                'district' => 'Dadu', 'tehsil' => 'Mehar', 'hub_id' => 'JH-DAD-01',
                'intake_date' => '2026-04-02', 'intake_time' => '14:17', 'mode' => 'Referral', 'source' => 'Police',
                'primary_issue' => 'Juvenile', 'secondary_issue' => 'Bail / diversion', 'urgency' => 'High',
                'pathway' => ['Legal Advice', 'Litigation', 'Court'],
                'status' => 'Active', 'disposition' => 'litigation', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => true, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => true,
                'risk' => 'High', 'last_update' => '2026-04-28',
                'summary' => 'Sixteen-year-old facing first-time petty theft charge. Juvenile Justice System Act invoked; diversion to community-based intervention being argued in lieu of trial.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. P. Kumar',
            ],
            [
                'case_uid' => 'CL-02443', 'case_ref' => 'CA-02443', 'encounter_id' => 'SE-09798',
                'name' => 'Zubaida B.', 'gender' => 'Female', 'age' => 32,
                'district' => 'Sukkur', 'tehsil' => 'Sukkur City', 'hub_id' => 'JH-SUK-01',
                'intake_date' => '2026-03-10', 'intake_time' => '10:14', 'mode' => 'Referral', 'source' => 'Shelter',
                'primary_issue' => 'GBV', 'secondary_issue' => 'Domestic violence', 'urgency' => 'Immediate',
                'pathway' => ['Legal Advice', 'Litigation', 'Court', 'Referral'],
                'status' => 'Active', 'disposition' => 'litigation', 'sla_met' => true,
                'is_gbv' => true, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => true,
                'risk' => 'High', 'last_update' => '2026-04-28',
                'summary' => 'Survivor of severe domestic violence with documented medical evidence. Protection order obtained; criminal complaint under DV Act being prosecuted in Sessions Court.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. N. Jatoi',
            ],
            [
                'case_uid' => 'CL-02436', 'case_ref' => 'CA-02436', 'encounter_id' => 'SE-09790',
                'name' => 'Tahira J.', 'gender' => 'Female', 'age' => 44,
                'district' => 'Hyderabad', 'tehsil' => 'Latifabad', 'hub_id' => 'JH-HYD-01',
                'intake_date' => '2026-01-19', 'intake_time' => '14:17', 'mode' => 'Walk-in', 'source' => 'Self',
                'primary_issue' => 'Inheritance', 'secondary_issue' => 'Share enforcement', 'urgency' => 'Medium',
                'pathway' => ['Legal Advice', 'Litigation', 'Court'],
                'status' => 'Active', 'disposition' => 'litigation', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => false,
                'risk' => 'Low', 'last_update' => '2026-04-28',
                'summary' => 'Daughter seeking enforcement of inheritance share denied by male siblings for 12 years. Civil suit for partition concluded; judgment reserved by Civil Court.',
                'language' => 'Urdu', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. F. Hussain',
            ],
            [
                'case_uid' => 'CL-02432', 'case_ref' => 'CA-02432', 'encounter_id' => 'SE-09784',
                'name' => 'Kareem D.', 'gender' => 'Male', 'age' => 49,
                'district' => 'Sanghar', 'tehsil' => 'Sanghar City', 'hub_id' => 'JH-SAN-01',
                'intake_date' => '2026-01-12', 'intake_time' => '09:05', 'mode' => 'Walk-in', 'source' => 'Self',
                'primary_issue' => 'Property', 'secondary_issue' => 'Ejectment', 'urgency' => 'Low',
                'pathway' => ['Legal Advice', 'Litigation', 'Court'],
                'status' => 'Active', 'disposition' => 'litigation', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => false,
                'risk' => 'Low', 'last_update' => '2026-04-28',
                'summary' => 'Property owner pursuing ejectment of tenant in default of rent for 14 months. Civil suit concluded; judgment reserved on ejectment with mesne profits.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. F. Hussain',
            ],
            [
                'case_uid' => 'CL-02418', 'case_ref' => 'CA-02418', 'encounter_id' => 'SE-09767',
                'name' => 'Rashida B.', 'gender' => 'Female', 'age' => 51,
                'district' => 'Sukkur', 'tehsil' => 'Sukkur City', 'hub_id' => 'JH-SUK-01',
                'intake_date' => '2025-12-02', 'intake_time' => '11:32', 'mode' => 'Walk-in', 'source' => 'Community',
                'primary_issue' => 'Inheritance', 'secondary_issue' => 'Share recovered', 'urgency' => 'Medium',
                'pathway' => ['Legal Advice', 'Litigation', 'Court'],
                'status' => 'Closed', 'disposition' => 'litigation', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => true,
                'risk' => 'Low', 'last_update' => '2026-04-19',
                'summary' => 'Widow successfully recovered inheritance share through Civil Court partition decree after extended proceedings. Decree executed; share registered in client\'s name.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. N. Jatoi',
            ],
            [
                'case_uid' => 'CL-02414', 'case_ref' => 'CA-02414', 'encounter_id' => 'SE-09763',
                'name' => 'Hassan I.', 'gender' => 'Male', 'age' => 27,
                'district' => 'Dadu', 'tehsil' => 'Mehar', 'hub_id' => 'JH-DAD-01',
                'intake_date' => '2025-12-01', 'intake_time' => '10:14', 'mode' => 'Walk-in', 'source' => 'Community',
                'primary_issue' => 'Criminal', 'secondary_issue' => 'Acquittal', 'urgency' => 'High',
                'pathway' => ['Legal Advice', 'Litigation', 'Court'],
                'status' => 'Closed', 'disposition' => 'litigation', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => true,
                'risk' => 'Medium', 'last_update' => '2026-04-22',
                'summary' => 'Defendant in criminal case acquitted by Sessions Court after defence demonstrated material contradictions in prosecution evidence. Client released; reputation restored.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. M. Soomro',
            ],
            [
                'case_uid' => 'CL-02411', 'case_ref' => 'CA-02411', 'encounter_id' => 'SE-09760',
                'name' => 'Nazia F.', 'gender' => 'Female', 'age' => 28,
                'district' => 'Shaheed Benazirabad', 'tehsil' => 'Nawabshah', 'hub_id' => 'JH-SBA-01',
                'intake_date' => '2026-01-10', 'intake_time' => '14:17', 'mode' => 'Referral', 'source' => 'Shelter',
                'primary_issue' => 'Family', 'secondary_issue' => 'Maintenance', 'urgency' => 'High',
                'pathway' => ['Legal Advice', 'Litigation', 'Court'],
                'status' => 'Closed', 'disposition' => 'litigation', 'sla_met' => true,
                'is_gbv' => true, 'is_child' => true, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => true,
                'risk' => 'High', 'last_update' => '2026-04-16',
                'summary' => 'Family Court ordered maintenance of Rs. 22,000/month for client and her two children plus arrears, after estranged husband failed to maintain them post-separation.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. R. Khan',
            ],
            [
                'case_uid' => 'CL-02408', 'case_ref' => 'CA-02408', 'encounter_id' => 'SE-09757',
                'name' => 'Salim Q.', 'gender' => 'Male', 'age' => 58,
                'district' => 'Hyderabad', 'tehsil' => 'Latifabad', 'hub_id' => 'JH-HYD-01',
                'intake_date' => '2025-12-29', 'intake_time' => '14:17', 'mode' => 'Walk-in', 'source' => 'Self',
                'primary_issue' => 'Property', 'secondary_issue' => 'Partial settlement', 'urgency' => 'Medium',
                'pathway' => ['Legal Advice', 'Litigation', 'Court'],
                'status' => 'Settlement', 'disposition' => 'litigation', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => false,
                'risk' => 'Low', 'last_update' => '2026-04-10',
                'summary' => 'Property dispute resolved through court-supervised settlement mid-trial. Both parties agreed to a compromise allocation; consent decree pronounced.',
                'language' => 'Urdu', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. F. Hussain',
            ],
            [
                'case_uid' => 'CL-02402', 'case_ref' => 'CA-02402', 'encounter_id' => 'SE-09751',
                'name' => 'Yasmin O.', 'gender' => 'Female', 'age' => 39,
                'district' => 'Dadu', 'tehsil' => 'Mehar', 'hub_id' => 'JH-DAD-01',
                'intake_date' => '2025-10-30', 'intake_time' => '13:48', 'mode' => 'Walk-in', 'source' => 'Community',
                'primary_issue' => 'Civil', 'secondary_issue' => 'Suit dismissed', 'urgency' => 'Low',
                'pathway' => ['Legal Advice', 'Litigation', 'Court'],
                'status' => 'Closed', 'disposition' => 'litigation', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => true,
                'risk' => 'Low', 'last_update' => '2026-04-06',
                'summary' => 'Civil suit for declaration dismissed by trial court for want of evidence. Client counselled on appeal options; declined to pursue further given costs.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. P. Kumar',
            ],
            // --- Historical archived cases ---
            [
                'case_uid' => 'CL-02391', 'case_ref' => 'CA-02391', 'encounter_id' => 'SE-09730',
                'name' => 'Aleem K.', 'gender' => 'Male', 'age' => 44,
                'district' => 'Sukkur', 'tehsil' => 'Rohri', 'hub_id' => 'JH-SUK-01',
                'intake_date' => '2025-09-12', 'intake_time' => '10:30', 'mode' => 'Walk-in', 'source' => 'Self',
                'primary_issue' => 'Documentation', 'secondary_issue' => 'CNIC', 'urgency' => 'Low',
                'pathway' => ['Documentation'],
                'status' => 'Closed', 'disposition' => 'advice-only', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => true,
                'risk' => 'Low', 'last_update' => '2025-09-26',
                'summary' => 'Daily-wage worker assisted with NADRA CNIC reissue after losing original card. Document linked to BISP enrolment to restore family stipend access.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'T. Panhwar (Paralegal)',
            ],
            [
                'case_uid' => 'CL-02398', 'case_ref' => 'CA-02398', 'encounter_id' => 'SE-09737',
                'name' => 'Bilqis F.', 'gender' => 'Female', 'age' => 36,
                'district' => 'Hyderabad', 'tehsil' => 'Qasimabad', 'hub_id' => 'JH-HYD-01',
                'intake_date' => '2025-10-04', 'intake_time' => '14:18', 'mode' => 'Walk-in', 'source' => 'Community',
                'primary_issue' => 'Family', 'secondary_issue' => 'Maintenance', 'urgency' => 'Medium',
                'pathway' => ['Legal Advice', 'Mediation'],
                'status' => 'Settlement', 'disposition' => 'adr', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => false,
                'risk' => 'Medium', 'last_update' => '2025-11-08',
                'summary' => 'Mother of two secured maintenance settlement through hub-led mediation. Three sessions concluded with monthly maintenance of Rs. 16,000 plus school fees agreed.',
                'language' => 'Urdu', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. R. Khan',
            ],
            [
                'case_uid' => 'CL-02422', 'case_ref' => 'CA-02422', 'encounter_id' => 'SE-09773',
                'name' => 'Zarina B.', 'gender' => 'Female', 'age' => 47,
                'district' => 'Sanghar', 'tehsil' => 'Tando Adam', 'hub_id' => 'JH-SAN-01',
                'intake_date' => '2025-12-08', 'intake_time' => '11:42', 'mode' => 'Walk-in', 'source' => 'Self',
                'primary_issue' => 'Inheritance', 'secondary_issue' => 'Share release', 'urgency' => 'Medium',
                'pathway' => ['Legal Advice', 'Mediation'],
                'status' => 'Settlement', 'disposition' => 'adr', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => true,
                'risk' => 'Low', 'last_update' => '2026-01-22',
                'summary' => 'Widow recovered inheritance share through mediation with brother-in-law. Sharia entitlement of one-eighth of agricultural holding settled in cash equivalent.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. F. Hussain',
            ],
            [
                'case_uid' => 'CL-02425', 'case_ref' => 'CA-02425', 'encounter_id' => 'SE-09776',
                'name' => 'Mohsin R.', 'gender' => 'Male', 'age' => 38,
                'district' => 'Shaheed Benazirabad', 'tehsil' => 'Sakrand', 'hub_id' => 'JH-SBA-01',
                'intake_date' => '2025-12-19', 'intake_time' => '09:05', 'mode' => 'Walk-in', 'source' => 'Self',
                'primary_issue' => 'Labour', 'secondary_issue' => 'Wage recovery', 'urgency' => 'Medium',
                'pathway' => ['Legal Advice', 'Mediation'],
                'status' => 'Closed', 'disposition' => 'adr', 'sla_met' => true,
                'is_gbv' => false, 'is_child' => false, 'is_minority' => false, 'is_disability' => false, 'is_underserved' => true,
                'risk' => 'Low', 'last_update' => '2026-02-14',
                'summary' => 'Skilled mason recovered Rs. 84,000 in unpaid wages from contractor through hub-led mediation. Two sessions concluded; full payment received.',
                'language' => 'Sindhi', 'consent' => true, 'returning_client' => false,
                'assigned_to' => 'Adv. P. Kumar',
            ],
        ];

        foreach ($cases as $caseData) {
            // Extract pathway before inserting
            $pathways = $caseData['pathway'] ?? [];
            unset($caseData['pathway']);

            $case = CaseRecord::firstOrCreate(
                ['case_uid' => $caseData['case_uid']],
                $caseData
            );

            // Insert pathways into the pivot table
            foreach ($pathways as $pathway) {
                DB::table('case_pathway')->insertOrIgnore([
                    'case_id'       => $case->id,
                    'pathway_value' => $pathway,
                    'created_at'    => now(),
                    'updated_at'    => now(),
                ]);
            }
        }
    }
}
