<?php

namespace Database\Seeders;

use App\Models\Evidence;
use Illuminate\Database\Seeder;

class EvidenceSeeder extends Seeder
{
    public function run(): void
    {
        $records = [
            ['evidence_uid' => 'EV-001', 'type' => 'recognition',
             'title' => 'Sindh Govt. Notification: Justice Hubs as official ADR providers',
             'summary' => 'Notification No. SOJ-2025/447 from the Law & Parliamentary Affairs Department recognising the Justice Hub network as authorised community ADR providers under Sindh Mediation Act 2018.',
             'date' => '2025-08-14', 'verified' => true, 'verified_by' => 'A. Mahar (M&E Lead)', 'verified_date' => '2025-08-22',
             'issuer' => 'Govt. of Sindh · Law & Parliamentary Affairs Dept.', 'hub_id' => null,
             'document_ref' => 'SOJ-2025/447', 'tags' => ['ADR', 'official-recognition', 'Sindh'],
             'linked_indicator' => 'G1'],
            ['evidence_uid' => 'EV-002', 'type' => 'recognition',
             'title' => 'District Judge endorsement letter — Hyderabad',
             'summary' => 'Letter from the District & Sessions Judge, Hyderabad, formally referring litigants to the Hyderabad Justice Hub for pre-litigation mediation in family matters.',
             'date' => '2025-11-03', 'verified' => true, 'verified_by' => 'F. Hussain (Senior Lawyer)', 'verified_date' => '2025-11-10',
             'issuer' => 'District & Sessions Court, Hyderabad', 'hub_id' => 'JH-HYD-01',
             'document_ref' => 'DSJ-HYD-2025/118', 'tags' => ['judicial-recognition', 'family-court'],
             'linked_indicator' => 'G1'],
            ['evidence_uid' => 'EV-003', 'type' => 'integration',
             'title' => 'NADRA MoU — formal documentation channel',
             'summary' => 'Memorandum of Understanding establishing NADRA registration centres as priority partners with same-day appointment slots for Hub-referred clients.',
             'date' => '2025-01-14', 'verified' => true, 'verified_by' => 'A. Mahar (M&E Lead)', 'verified_date' => '2025-01-20',
             'issuer' => 'NADRA · Sindh Region', 'hub_id' => null,
             'document_ref' => 'NADRA-LAS-2025/01', 'tags' => ['MoU', 'documentation', 'partnership'],
             'linked_indicator' => 'G2'],
            ['evidence_uid' => 'EV-004', 'type' => 'integration',
             'title' => "Sindh Police Women's Desk · referral protocol",
             'summary' => 'Standing protocol for two-way referrals between Justice Hubs and Sindh Police Women\'s Protection Desks for GBV cases. Includes shared SOP and joint training.',
             'date' => '2025-04-21', 'verified' => true, 'verified_by' => 'F. Hussain (Senior Lawyer)', 'verified_date' => '2025-04-28',
             'issuer' => "Sindh Police · IGP's office", 'hub_id' => null,
             'document_ref' => 'SP-LAS-2025/14', 'tags' => ['MoU', 'GBV', 'police', 'protocol'],
             'linked_indicator' => 'G2'],
            ['evidence_uid' => 'EV-005', 'type' => 'integration',
             'title' => 'BISP integration — beneficiary verification protocol',
             'summary' => 'Joint procedure with the Benazir Income Support Programme allowing Hub paralegals to verify and resolve BISP enrolment issues at the local level.',
             'date' => '2025-05-19', 'verified' => true, 'verified_by' => 'A. Mahar (M&E Lead)', 'verified_date' => '2025-05-26',
             'issuer' => 'BISP · Sindh', 'hub_id' => null,
             'document_ref' => 'BISP-LAS-2025/07', 'tags' => ['MoU', 'social-protection'],
             'linked_indicator' => 'G2'],
            ['evidence_uid' => 'EV-006', 'type' => 'integration',
             'title' => 'Sindh Bar Council · pro bono referral list',
             'summary' => 'Justice Hubs included in the official Sindh Bar Council pro bono referral mechanism for cases beyond Hub representation capacity.',
             'date' => '2025-09-08', 'verified' => true, 'verified_by' => 'F. Hussain (Senior Lawyer)', 'verified_date' => '2025-09-15',
             'issuer' => 'Sindh Bar Council', 'hub_id' => null,
             'document_ref' => 'SBC-2025/214', 'tags' => ['MoU', 'legal-profession'],
             'linked_indicator' => 'G2'],
            ['evidence_uid' => 'EV-007', 'type' => 'integration',
             'title' => 'Civil Hospital Karachi — MLC fast-track',
             'summary' => 'Standing arrangement for Hub-referred GBV clients to receive priority Medico-Legal Certificate processing.',
             'date' => '2025-06-14', 'verified' => true, 'verified_by' => 'F. Hussain (Senior Lawyer)', 'verified_date' => '2025-06-21',
             'issuer' => 'Civil Hospital Karachi', 'hub_id' => 'JH-SAN-01',
             'document_ref' => 'CHK-2025/MLC-44', 'tags' => ['MoU', 'health', 'GBV'],
             'linked_indicator' => 'G2'],
            ['evidence_uid' => 'EV-008', 'type' => 'replication',
             'title' => 'Punjab pilot · 2 hubs in DG Khan and Bahawalpur',
             'summary' => 'Punjab Govt. funded a pilot replication of the Justice Hub model in DG Khan and Bahawalpur districts based on the Sindh evidence package. Operational since Q1 2026.',
             'date' => '2026-01-12', 'verified' => true, 'verified_by' => 'A. Mahar (M&E Lead)', 'verified_date' => '2026-01-30',
             'issuer' => 'Govt. of Punjab · Law Dept.', 'hub_id' => null,
             'document_ref' => 'PB-LAS-2026/001', 'tags' => ['replication', 'scale-up', 'Punjab'],
             'linked_indicator' => 'G3'],
            ['evidence_uid' => 'EV-009', 'type' => 'policy-citation',
             'title' => 'National Judicial Policy Making Cmte. citation',
             'summary' => 'Justice Hub case data cited in the NJPMC paper "Pre-litigation diversion in family law" as evidence for the recommended national framework.',
             'date' => '2025-10-22', 'verified' => true, 'verified_by' => 'A. Mahar (M&E Lead)', 'verified_date' => '2025-11-05',
             'issuer' => 'National Judicial Policy Making Committee', 'hub_id' => null,
             'document_ref' => 'NJPMC-2025/14', 'tags' => ['policy', 'judicial-reform'],
             'linked_indicator' => 'G4'],
            ['evidence_uid' => 'EV-010', 'type' => 'policy-citation',
             'title' => 'World Bank · Pakistan Justice Sector Review',
             'summary' => 'Justice Hub satisfaction and SLA data quoted in the 2025 World Bank Justice Sector Review as evidence of community-based service delivery effectiveness.',
             'date' => '2025-12-08', 'verified' => true, 'verified_by' => 'A. Mahar (M&E Lead)', 'verified_date' => '2025-12-15',
             'issuer' => 'World Bank · Pakistan Country Office', 'hub_id' => null,
             'document_ref' => 'WB-PJSR-2025', 'tags' => ['policy', 'donor'],
             'linked_indicator' => 'G4'],
            ['evidence_uid' => 'EV-011', 'type' => 'policy-citation',
             'title' => 'Senate Cmte. on Human Rights · written submission used',
             'summary' => "Hub data on minority documentation cases included in the Senate Standing Committee's 2025 report on minority rights.",
             'date' => '2025-07-19', 'verified' => true, 'verified_by' => 'A. Mahar (M&E Lead)', 'verified_date' => '2025-07-30',
             'issuer' => 'Senate of Pakistan · Human Rights Cmte.', 'hub_id' => null,
             'document_ref' => 'SCH-2025/41', 'tags' => ['policy', 'parliamentary'],
             'linked_indicator' => 'G4'],
            ['evidence_uid' => 'EV-012', 'type' => 'policy-citation',
             'title' => 'EU funding decision · Phase II Sindh expansion',
             'summary' => 'EU Delegation cited Hub Phase I results as decisive evidence for approving Phase II expansion (€2.4M, 2026-2028).',
             'date' => '2025-09-30', 'verified' => true, 'verified_by' => 'A. Mahar (M&E Lead)', 'verified_date' => '2025-10-12',
             'issuer' => 'EU Delegation to Pakistan', 'hub_id' => null,
             'document_ref' => 'EU-PK-2025/118', 'tags' => ['donor', 'funding-decision'],
             'linked_indicator' => 'G4'],
            ['evidence_uid' => 'EV-013', 'type' => 'policy-citation',
             'title' => "British Council · Voices for Justice programme",
             'summary' => "Hub paralegal model adopted as the community-engagement template for British Council's Voices for Justice programme in 4 additional districts.",
             'date' => '2025-11-25', 'verified' => true, 'verified_by' => 'A. Mahar (M&E Lead)', 'verified_date' => '2025-12-03',
             'issuer' => 'British Council Pakistan', 'hub_id' => null,
             'document_ref' => 'BC-VfJ-2025/09', 'tags' => ['donor', 'replication'],
             'linked_indicator' => 'G4'],
            ['evidence_uid' => 'EV-014', 'type' => 'analytical-product',
             'title' => 'Quarterly Trends Report Q4 2025',
             'summary' => 'Public quarterly trends report covering case mix, GBV intake, and rural reach. Distributed to 12 government and donor counterparts.',
             'date' => '2026-01-22', 'verified' => true, 'verified_by' => 'A. Mahar (M&E Lead)', 'verified_date' => '2026-01-25',
             'issuer' => 'LAS · Justice Hub M&E Team', 'hub_id' => null,
             'document_ref' => 'LAS-Q4-2025', 'tags' => ['quarterly', 'public'],
             'linked_indicator' => 'OP4.4'],
            ['evidence_uid' => 'EV-015', 'type' => 'analytical-product',
             'title' => 'GBV-sensitive ADR · field practice paper',
             'summary' => 'Practice paper documenting the Hub approach to GBV-sensitive mediation, with case studies and decision-tree for safety screening.',
             'date' => '2025-08-30', 'verified' => true, 'verified_by' => 'F. Hussain (Senior Lawyer)', 'verified_date' => '2025-09-08',
             'issuer' => 'LAS · Justice Hub Programme', 'hub_id' => null,
             'document_ref' => 'LAS-PP-2025/02', 'tags' => ['practice-paper', 'GBV', 'ADR'],
             'linked_indicator' => 'OP4.4'],
            ['evidence_uid' => 'EV-016', 'type' => 'analytical-product',
             'title' => 'Documentation barriers faced by religious minorities',
             'summary' => 'Research brief drawing on Hub case data showing the documentation barriers faced by Hindu and Christian clients, with policy recommendations.',
             'date' => '2025-06-15', 'verified' => true, 'verified_by' => 'A. Mahar (M&E Lead)', 'verified_date' => '2025-06-25',
             'issuer' => 'LAS · Justice Hub Programme', 'hub_id' => null,
             'document_ref' => 'LAS-RB-2025/01', 'tags' => ['research', 'minority', 'documentation'],
             'linked_indicator' => 'OP4.4'],
            ['evidence_uid' => 'EV-017', 'type' => 'analytical-product',
             'title' => 'Annual Report 2025 · Justice Hub Initiative',
             'summary' => 'Public annual report. Distributed to 200+ stakeholders. Cited by the World Bank review and Senate Cmte. (linked: EV-010, EV-011).',
             'date' => '2026-02-28', 'verified' => true, 'verified_by' => 'A. Mahar (M&E Lead)', 'verified_date' => '2026-03-05',
             'issuer' => 'LAS · Justice Hub Programme', 'hub_id' => null,
             'document_ref' => 'LAS-AR-2025', 'tags' => ['annual-report', 'public'],
             'linked_indicator' => 'OP4.4'],
            ['evidence_uid' => 'EV-018', 'type' => 'analytical-product',
             'title' => 'Cost-effectiveness analysis · 2025 baseline',
             'summary' => 'Internal VfM analysis establishing per-case cost-effectiveness baselines across the four Justice Hub service pillars.',
             'date' => '2025-12-15', 'verified' => true, 'verified_by' => 'A. Mahar (M&E Lead)', 'verified_date' => '2025-12-22',
             'issuer' => 'LAS · M&E Team', 'hub_id' => null,
             'document_ref' => 'LAS-VFM-2025', 'tags' => ['VfM', 'cost-analysis', 'internal'],
             'linked_indicator' => 'OP4.4'],
            ['evidence_uid' => 'EV-019', 'type' => 'analytical-product',
             'title' => 'Juvenile diversion · case-study compilation',
             'summary' => 'Compilation of 14 anonymised juvenile diversion case studies. Used in lawyer training and shared with the Sukkur Child Protection Unit.',
             'date' => '2025-10-05', 'verified' => false, 'verified_by' => null, 'verified_date' => null,
             'issuer' => 'LAS · Sukkur Hub', 'hub_id' => 'JH-SUK-01',
             'document_ref' => 'LAS-CS-2025/03', 'tags' => ['case-study', 'juvenile'],
             'linked_indicator' => 'OP4.4'],
            ['evidence_uid' => 'EV-020', 'type' => 'recognition',
             'title' => 'KP Govt. expression of interest (PRELIMINARY)',
             'summary' => 'Letter from KP Law Dept. expressing interest in studying the Justice Hub model for possible adoption. Awaiting formal MoU before counting toward G1.',
             'date' => '2026-03-22', 'verified' => false, 'verified_by' => null, 'verified_date' => null,
             'issuer' => 'Govt. of KP · Law Dept.', 'hub_id' => null,
             'document_ref' => 'KP-LAS-2026/EOI-04', 'tags' => ['preliminary', 'KP'],
             'linked_indicator' => 'G1'],
        ];

        foreach ($records as $data) {
            Evidence::firstOrCreate(['evidence_uid' => $data['evidence_uid']], $data);
        }
    }
}
