<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
    body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1a1a1a; margin: 0; padding: 20px; }
    h1 { font-size: 22px; font-weight: 700; margin-bottom: 4px; }
    h2 { font-size: 15px; font-weight: 700; margin: 18px 0 6px; border-bottom: 2px solid #2d6a4f; padding-bottom: 4px; }
    .subtitle { font-size: 11px; color: #666; margin-bottom: 20px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 16px; font-size: 11px; }
    th { background: #2d6a4f; color: #fff; padding: 6px 8px; text-align: left; }
    td { padding: 5px 8px; border-bottom: 1px solid #eee; }
    .rag-green { background: #d4edda; color: #155724; padding: 2px 6px; border-radius: 3px; font-size: 10px; }
    .rag-amber { background: #fff3cd; color: #856404; padding: 2px 6px; border-radius: 3px; font-size: 10px; }
    .rag-red { background: #f8d7da; color: #721c24; padding: 2px 6px; border-radius: 3px; font-size: 10px; }
    .metric-grid { display: table; width: 100%; margin-bottom: 16px; }
    .metric-box { display: table-cell; width: 25%; padding: 10px; background: #f8f9fa; border-right: 1px solid #dee2e6; vertical-align: top; }
    .metric-box:last-child { border-right: none; }
    .metric-val { font-size: 20px; font-weight: 700; color: #2d6a4f; }
    .metric-lbl { font-size: 10px; color: #666; text-transform: uppercase; letter-spacing: 0.05em; }
    .footer { margin-top: 30px; font-size: 10px; color: #999; border-top: 1px solid #eee; padding-top: 8px; }
</style>
</head>
<body>
<h1>Justice Hub — Impact Report</h1>
<div class="subtitle">
    {{ ucfirst($template) }} Report &bull; Period: {{ $period }} &bull; Generated: {{ $generated }}
</div>

<h2>Key Metrics Summary</h2>
<div class="metric-grid">
    <div class="metric-box">
        <div class="metric-val">{{ $cases->count() }}</div>
        <div class="metric-lbl">Total Cases</div>
    </div>
    <div class="metric-box">
        <div class="metric-val">{{ $feedback->count() > 0 ? round($feedback->avg('score_overall'),1) : '—' }}</div>
        <div class="metric-lbl">Avg Feedback Score</div>
    </div>
    <div class="metric-box">
        <div class="metric-val">{{ number_format($outreach->sum('total_participants')) }}</div>
        <div class="metric-lbl">Outreach Participants</div>
    </div>
    <div class="metric-box">
        <div class="metric-val">{{ $ragCounts['green'] }}/{{ $indicators->count() }}</div>
        <div class="metric-lbl">Indicators On Track</div>
    </div>
</div>

<h2>Indicator Performance</h2>
<table>
    <thead>
        <tr>
            <th>Code</th>
            <th>Indicator</th>
            <th>Target</th>
            <th>Actual</th>
            <th>Unit</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach($indicators as $ind)
        <tr>
            <td>{{ $ind->code }}</td>
            <td>{{ $ind->name }}</td>
            <td>{{ $ind->target }}</td>
            <td>{{ $ind->actual }}</td>
            <td>{{ $ind->unit }}</td>
            <td><span class="rag-{{ $ind->rag }}">{{ strtoupper($ind->rag) }}</span></td>
        </tr>
        @endforeach
    </tbody>
</table>

<div class="footer">
    Confidential — Justice Hub Programme &bull; Generated by JusticeHub CRM &bull; {{ $generated }}
</div>
</body>
</html>
